### ISSUE TITLE
New Mode Suggestion - # of Queues

### ISSUE THREAD

**Issue by DeepSeaCatz** [Pos13/comfyui-cyclist#12]
Hi there, I found your workflow/node pack on [Civitai](https://civitai.com/models/341750/cyclist-or-comfyui-custom-nodes).

I love the concept as I often let my PC queue lots of images for hours, but don't want to over do it all night. With the Flux image generation, it often takes almost a minute per queue and 5 minutes for upscale. Would it be possible to add a new mode in the Generation Timer to add the number of finished Queue/Cycles? This would mean that I had enough time to finish an entire generation and I could limit the amount of generation by let say 200.

Not sure quite sure if it'll be doable as currently it's a simple timer, but this would be more practical for sure.

Thanks!

**Comment by Pos13** [comment]
You can simply do it with existing **Recall Int**/**Memorize Int** nodes. Just add 1 to whatever variable every cycle, and call an **Interrupt** node if it exceed 200. You can kinda see it in the example [MultiplePersons](https://github.com/Pos13/comfyui-cyclist/blob/main/workflows/MultiplePersons.png) workflow, as it stops when enough persons generated.
