### ISSUE TITLE
[FR] Add support for new header/menu

### ISSUE THREAD

**Issue by DrJKL** [Pos13/comfyui-cyclist#5]
https://github.com/comfyanonymous/ComfyUI/pull/3112

I think mostly just putting the New Cycle button in a reasonable place.

**Comment by DrJKL** [comment]
Oh, and fixing the unchecking of autoqueue

**Comment by DrJKL** [comment]
Could also do something with this https://github.com/Comfy-Org/ComfyUI_frontend/pull/215

**Comment by Pos13** [comment]
I saw your PR, I'll check it later.

**Comment by Pos13** [comment]
done by #10 and 520da53
