### ISSUE TITLE
[FR] Compare Anything: String contains/startsWith/etc

### ISSUE THREAD

**Issue by DrJKL** [Pos13/comfyui-cyclist#6]
It has equals, but when the caption is verbose it doesn't trigger.

## Example
"two people are in picture in picture's ordinal it is two woman and two dog's head and hair" doesn't *equal* "two"

**Comment by DrJKL** [comment]
WAS has a Text Contains node, but it feels like if someone wanted to minimize custom node installations it'd be good to support it in here.

**Comment by Pos13** [comment]
"_two people are in picture in picture's ordinal it is two woman and two dog's head and hair_" is greater than "_two_", alphabetical order. Node works as intented.
I made math and string utilities as necessary evil to minimize custom node installations, but I want to keep them as basic as possible. For extra functionality use dedicated custom nodes.
