### ISSUE TITLE
[FR] If recall latent has a latent to recall, don't trigger input nodes

### ISSUE THREAD

**Issue by DrJKL** [Pos13/comfyui-cyclist#8]
I think probably by using [IS_CHANGED](https://docs.comfy.org/essentials/custom_node_server_overview#is-changed)?

**Comment by DrJKL** [comment]
Wait, this should already be happening: https://github.com/Pos13/comfyui-cyclist/blob/main/cyclist.py#L191

**Comment by DrJKL** [comment]
I'm not sure if there's a way to say that you have changed but don't need to poll one of the inputs

**Comment by DrJKL** [comment]
Similar issue: https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/671

**Comment by Pos13** [comment]
Can't replicate. It doesn't recall input without reason, check on **CatStack** workflow: https://github.com/Pos13/comfyui-cyclist/blob/main/workflows/CatStack.png
Related code: https://github.com/Pos13/comfyui-cyclist/blob/520da5379b19cf283ed3bb1a2bf097514c588816/cyclist.py#L381
